region: us-east-1
stage: BUILD_ENV
env: BUILD_ENV
role: BUILD_LAMBDA_ROLE_ARN
accessControlAllowOrigin: "*"
apiId: BUILD_API_ID
apiRootId: BUILD_API_ROOT_ID
# Para el servicio de deudas
wsNube:
    wsGrantType: BUILD_WSN_GRANT_TYPE
    wsClientSecret: BUILD_WSN_CLIENT_SECRET
    wsClientId: BUILD_WSN_CLIENT_ID
    wsScope: BUILD_WSN_SCOPE
    wsGenToken: BUILD_WSN_HOST_TOKEN
    wsHostNube: BUILD_WSN_HOST
wsNubePerfilamiento:
    wspGrantType: BUILD_INFO_PERFILES_GRANT_TYPE
    wspClientSecret: BUILD_INFO_PERFILES_CLIENT_SECRET
    wspClientId: BUILD_INFO_PERFILES_CLIENT_ID
    wspScope: BUILD_INFO_PERFILES_SCOPE
    wspHostNube: BUILD_INFO_PERFILES_HOST
    


