service: app-impuesto-digital

custom: ${file(./config.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${self:custom.stage}
  role: ${self:custom.role}
  stackName: tgr-${self:custom.env}-${self:service}
  stackTags:
    Application: ${self:service}
    Env: ${self:custom.stage}
  apiGateway:
    restApiId: ${self:custom.apiId}
    restApiRootResourceId: ${self:custom.apiRootId}
  environment:
    REST_TOKEN_GRANT_TYPE: ${self:custom.wsNube.wsGrantType}
    REST_TOKEN_SCOPE: ${self:custom.wsNube.wsScope}
    REST_TOKEN_CLIENT_ID: ${self:custom.wsNube.wsClientId}
    REST_TOKEN_CLIENT_SECRET: ${self:custom.wsNube.wsClientSecret}
    HOST_TOKEN: ${self:custom.wsNube.wsGenToken}
    ENV: ${self:custom.env}
    HOSTNUBE:  ${self:custom.wsNube.wsHostNube}

   
package:
  exclude:
  - package-lock.json
  - package.json

functions:
  getDeuda:
    name: tgr-${self:custom.env}-${self:service}-presentaCuentasME
    handler: consultaCuentaMonex.handler
    timeout: 30
    events:
    - http:
        path: impdigital/presentaCuentasME
        method: post
        cors: true
        
  getMovimiento:
    name: tgr-${self:custom.env}-${self:service}-getMovimiento
    handler: consultaMovimiento.handler
    timeout: 30
    events:
    - http:
        path: impdigital/presentaMovsME/{mov}
        method: get
        cors: true