version: 0.2
phases:
    install:
        commands:
            - cd front
            - touch ${CODEBUILD_SRC_DIR}/front/src/environments/environment.ts
            - cp ${CODEBUILD_SRC_DIR}/front/src/environments/environment.ts ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts
            - sed -i "s;BUILD_API_ENDPOINT;${BUILD_API_ENDPOINT};g" ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts
            - sed -i "s;BUILD_AUTH_AUTHORIZE_URL;${BUILD_AUTH_AUTHORIZE_URL};g" ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts
            - sed -i "s;BUILD_AUTH_LOGOUT_URL;${BUILD_AUTH_LOGOUT_URL};g" ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts
            - sed -i "s;BUILD_AUTH_CLIENT_ID;${BUILD_AUTH_CLIENT_ID};g" ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts
            - sed -i "s;BUILD_APP_REDIRECT_LOGIN_URL;${BUILD_APP_REDIRECT_LOGIN_URL};g" ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts
            - sed -i "s;BUILD_APP_REDIRECT_LOGOUT_URL;${BUILD_APP_REDIRECT_LOGOUT_URL};g" ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts
            - sudo apt-get update -y
            - npm install -g @angular/cli@6.0.8
            - npm install
    build:
        commands:
            - cd ${CODEBUILD_SRC_DIR}/front
            - more ${CODEBUILD_SRC_DIR}/front/src/environments/environment.prod.ts 
            - ng serve --configuration es5
            - ng build --prod 
            # - echo "---------------UBICACION DEL ARCHIVO----------------"
            # - pwd
            # - echo "--------------- build ----------------"
            # - ng build --prod
            # - echo "--------------- buscarndo archivos ----------------"
            # - ls -la
            # - cd dist
            # - ls -la
            # - cd base-front
            # - ls -la

    post_build:
        commands:
            - aws s3 cp dist/front s3://${S3_BUCKET}/tmp --recursive --acl public-read
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'
